#if !canImport(ObjectiveC)
    import XCTest

    extension LogTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__LogTests = [
            ("testExample", testExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(LogTests.__allTests__LogTests),
        ]
    }
#endif
